version: "3"
services:
  db:
    container_name: wp-database
    build: ./db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    networks:
      - mysql-phpmyadmin
  phpmyadmin:
    container_name: wp-phpmyadmin
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mysql-phpmyadmin
  webserver:
    container_name: wp-site
    depends_on:
      - db
    build: ./webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: funk
      WORDPRESS_DB_PASSWORD: funk
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
    networks:
      - wordpress-network
networks:
  mysql-phpmyadmin:
  wordpress-network:
volumes:
  db_data: